[[ISSUERS]]
address = "rDzDFNxV1SmhdRFJUGu7HBZHN57j8Cx3n9"
name = "Bullish on XRP"

[[TOKENS]]
issuer = "rDzDFNxV1SmhdRFJUGu7HBZHN57j8Cx3n9"
currency = "Bullish"
name = "Bullish on XRP"
desc = "Bullish on XRP (Bullish) is a digital currency on the XRPL."
icon = "https://bullishtoken.github.io/icons/bullish.png"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com/BullishTokenxrp"
type = "socialmedia"
title = "Follow on Twitter"
